# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7de781ba1edbf1b2d2b240c4f31c9dfbff5d18b9aaf1c5cef23fcae1d087504a377dd0f1759691eb2393405a7c457ae650f3cb5478191bc52b72ed59721add

test:
  secret_key_base: cd9bdcfcbef623addcd60b714272335cc967138ec7e19be0423541b42f2703e0f7c3bf9f63a25b983c6012ff185bf87b77eed9e40954e2152e20ee5b2084feaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
